name: Deployment

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    env:
      AWS_CLI_VERSION: 2.2.22
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
        python-version: 3.8
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8'
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Install AWS cli
      uses: unfor19/install-aws-cli-action@master
      with:
          version: ${{ env.AWS_CLI_VERSION }}        
    - name: Copy config file to S3
      run: |
        aws s3 cp exchange configuration - prod.csv s3://bigabid-de-staging/temp_files/bigabid-exchange-config/exchange configuration - prod.csv
